<?php

/** @generate-class-entries */

// AUTOGENERATED FILE - DO NOT EDIT.
//
// This file has been automatically generated by FrankenPHP extension generator
// and should not be edited as it will be overwritten when running the
// extension generator again.
//
// You may edit the file and remove this comment if you plan to manually maintain
// this file going forward.

function hazedb_fetch(string $sql, mixed $args = null): ?array {}

function hazedb_fetchall(string $sql, mixed $args = null): ?array {}

function hazedb_fetchall_json(string $sql, mixed $args = null): ?string {}

function hazedb_exec(string $sql, mixed $args = null): int {}

function hazedb_ping(): string {}


