package hazedb_ext

// AUTOGENERATED FILE - DO NOT EDIT.
//
// This file has been automatically generated by FrankenPHP extension generator
// and should not be edited as it will be overwritten when running the
// extension generator again.
//
// You may edit the file and remove this comment if you plan to manually maintain
// this file going forward.

// #include <stdlib.h>
// #include "hazedb_ext.h"
import "C"
import (
	_ "runtime/cgo"
	"unsafe"

	"github.com/dunglas/frankenphp"
)

func init() {
	frankenphp.RegisterExtension(unsafe.Pointer(&C.hazedb_ext_module_entry))
}

//export go_hazedb_fetch
func go_hazedb_fetch(sql *C.zend_string, args *C.zval) (ret unsafe.Pointer) {
	return hazedb_fetch(sql, args)
}

//export go_hazedb_fetchall
func go_hazedb_fetchall(sql *C.zend_string, args *C.zval) (ret unsafe.Pointer) {
	return hazedb_fetchall(sql, args)
}

//export go_hazedb_fetchall_json
func go_hazedb_fetchall_json(sql *C.zend_string, args *C.zval) (ret unsafe.Pointer) {
	return hazedb_fetchall_json(sql, args)
}

//export go_hazedb_exec
func go_hazedb_exec(sql *C.zend_string, args *C.zval) (ret int64) {
	return hazedb_exec(sql, args)
}

//export go_hazedb_meta
func go_hazedb_meta() (ret unsafe.Pointer) {
	return hazedb_meta()
}

//export go_hazedb_ping
func go_hazedb_ping() unsafe.Pointer {
	return hazedb_ping()
}
