// AUTOGENERATED FILE - DO NOT EDIT.
//
// This file has been automatically generated by FrankenPHP extension generator
// and should not be edited as it will be overwritten when running the
// extension generator again.
//
// You may edit the file and remove this comment if you plan to manually maintain
// this file going forward.

#include <php.h>
#include <Zend/zend_API.h>
#include <Zend/zend_hash.h>
#include <Zend/zend_types.h>
#include <stddef.h>

#include "hazedb_ext.h"
#include "hazedb_ext_arginfo.h"
#include "_cgo_export.h"


PHP_MINIT_FUNCTION(hazedb_ext) {
    
    return SUCCESS;
}

zend_module_entry hazedb_ext_module_entry = {STANDARD_MODULE_HEADER,
                                         "hazedb_ext",
                                         ext_functions,             /* Functions */
                                         PHP_MINIT(hazedb_ext),  /* MINIT */
                                         NULL,                      /* MSHUTDOWN */
                                         NULL,                      /* RINIT */
                                         NULL,                      /* RSHUTDOWN */
                                         NULL,                      /* MINFO */
                                         "1.0.0",                   /* Version */
                                         STANDARD_MODULE_PROPERTIES};
PHP_FUNCTION(hazedb_fetch)
{
    zend_string *sql = NULL;
    zval *args = NULL;
    ZEND_PARSE_PARAMETERS_START(1, 2)
        Z_PARAM_STR(sql)
        Z_PARAM_OPTIONAL
        Z_PARAM_ZVAL(args)
    ZEND_PARSE_PARAMETERS_END();
    zend_array *result = go_hazedb_fetch(sql, args);
    if (result) {
        RETURN_ARR(result);
    }

	RETURN_NULL();
}

PHP_FUNCTION(hazedb_fetchall)
{
    zend_string *sql = NULL;
    zval *args = NULL;
    ZEND_PARSE_PARAMETERS_START(1, 2)
        Z_PARAM_STR(sql)
        Z_PARAM_OPTIONAL
        Z_PARAM_ZVAL(args)
    ZEND_PARSE_PARAMETERS_END();
    zend_array *result = go_hazedb_fetchall(sql, args);
    if (result) {
        RETURN_ARR(result);
    }

	RETURN_NULL();
}

PHP_FUNCTION(hazedb_fetchall_json)
{
    zend_string *sql = NULL;
    zval *args = NULL;
    ZEND_PARSE_PARAMETERS_START(1, 2)
        Z_PARAM_STR(sql)
        Z_PARAM_OPTIONAL
        Z_PARAM_ZVAL(args)
    ZEND_PARSE_PARAMETERS_END();
    zend_string *result = go_hazedb_fetchall_json(sql, args);
    if (result) {
        RETURN_STR(result);
    }

	RETURN_NULL();
}

PHP_FUNCTION(hazedb_exec)
{
    zend_string *sql = NULL;
    zval *args = NULL;
    ZEND_PARSE_PARAMETERS_START(1, 2)
        Z_PARAM_STR(sql)
        Z_PARAM_OPTIONAL
        Z_PARAM_ZVAL(args)
    ZEND_PARSE_PARAMETERS_END();
    long result = go_hazedb_exec(sql, args);
    RETURN_LONG(result);
}

PHP_FUNCTION(hazedb_meta)
{
    ZEND_PARSE_PARAMETERS_NONE();
    zend_string *result = go_hazedb_meta();
    if (result) {
        RETURN_STR(result);
    }

	RETURN_NULL();
}

PHP_FUNCTION(hazedb_ping)
{
    ZEND_PARSE_PARAMETERS_NONE();
    zend_string *result = go_hazedb_ping();
    if (result) {
        RETURN_STR(result);
    }

	RETURN_NULL();
}

