package hazedb_ext

// AUTOGENERATED FILE - DO NOT EDIT.
//
// This file has been automatically generated by FrankenPHP extension generator
// and should not be edited as it will be overwritten when running the
// extension generator again.
//
// You may edit the file and remove this comment if you plan to manually maintain
// this file going forward.

// #include <stdlib.h>
// #include "hazedb_ext.h"
import "C"
import (
	_ "runtime/cgo"
	"unsafe"

	"github.com/dunglas/frankenphp"
)

func init() {
	frankenphp.RegisterExtension(unsafe.Pointer(&C.hazedb_ext_module_entry))
}

//export go_hazedb_query
func go_hazedb_query(sql *C.zend_string, argsJSON *C.zend_string) unsafe.Pointer {
	return hazedb_query(sql, argsJSON)
}

//export go_hazedb_exec
func go_hazedb_exec(sql *C.zend_string, argsJSON *C.zend_string) unsafe.Pointer {
	return hazedb_exec(sql, argsJSON)
}

//export go_hazedb_uuidv7
func go_hazedb_uuidv7() unsafe.Pointer {
	return hazedb_uuidv7()
}
