package hazedb_ext

// AUTOGENERATED FILE - DO NOT EDIT.
//
// This file has been automatically generated by FrankenPHP extension generator
// and should not be edited as it will be overwritten when running the
// extension generator again.
//
// You may edit the file and remove this comment if you plan to manually maintain
// this file going forward.

// #include <stdlib.h>
// #include "hazedb_ext.h"
import "C"
import (
	_ "runtime/cgo"
	"unsafe"

	"github.com/dunglas/frankenphp"
)

func init() {
	frankenphp.RegisterExtension(unsafe.Pointer(&C.hazedb_ext_module_entry))
}

//export go_hazedb_query
func go_hazedb_query(sql *C.zend_string, argsJSON *C.zend_string) unsafe.Pointer {
	return hazedb_query(sql, argsJSON)
}

//export go_hazedb_exec
func go_hazedb_exec(sql *C.zend_string, argsJSON *C.zend_string) unsafe.Pointer {
	return hazedb_exec(sql, argsJSON)
}

//export go_hazedb_query_arr
func go_hazedb_query_arr(sql *C.zend_string, argsStr *C.zend_string) unsafe.Pointer {
	return hazedb_query_arr(sql, argsStr)
}

//export go_hazedb_get
func go_hazedb_get(sql *C.zend_string, idStr *C.zend_string) unsafe.Pointer {
	return hazedb_get(sql, idStr)
}

//export go_hazedb_exec_arr
func go_hazedb_exec_arr(sql *C.zend_string, args *C.zend_array) unsafe.Pointer {
	return hazedb_exec_arr(sql, args)
}

//export go_hazedb_ping
func go_hazedb_ping() unsafe.Pointer {
	return hazedb_ping()
}
