<?php

/** @generate-class-entries */

// AUTOGENERATED FILE - DO NOT EDIT.
//
// This file has been automatically generated by FrankenPHP extension generator
// and should not be edited as it will be overwritten when running the
// extension generator again.
//
// You may edit the file and remove this comment if you plan to manually maintain
// this file going forward.

function hazedb_query(string $sql, string $args): ?string {}

function hazedb_exec(string $sql, string $args): ?string {}

function hazedb_query_arr(string $sql, string $args): ?array {}

function hazedb_get(string $sql, string $id): ?array {}

function hazedb_exec_arr(string $sql, array $args): ?string {}

function hazedb_ping(): string {}


